blog/urls.py
from django.urls import path
from . import views
 
app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:year>/<int:month>/<int:day>/<slug:slug>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<slug:slug>/edit/', views.post_edit, name='post_edit'),
    path('category/<slug:slug>/', views.category_list, name="category_list"),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('comment/add/<int:post_id>', views.comment_form, name='comment_form'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta
      name="description"
      content="Orbitor,business,company,agency,modern,bootstrap4,tech,software"
    />
    <meta name="author" content="themefisher.com" />

    <title>Novena- Health & Care Medical template</title>

    <!-- Favicon -->
    <link
      rel="shortcut icon"
      type="image/x-icon"
      href="{% static 'images/favicon.ico' %}"
    />

    <!-- bootstrap.min css -->
    <link
      rel="stylesheet"
      href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}"
    />
    <!-- Icon Font Css -->
    <link
      rel="stylesheet"
      href="{% static 'plugins/icofont/icofont.min.css' %}"
    />
    <!-- Slick Slider  CSS -->
    <link
      rel="stylesheet"
      href="{% static 'plugins/slick-carousel/slick/slick.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'plugins/slick-carousel/slick/slick-theme.css' %}"
    />

    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>

  <body id="top">
    <header>
      <div class="header-top-bar">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-lg-6">
              <ul class="top-bar-info list-inline-item pl-0 mb-0">
                <li class="list-inline-item">
                  <a href="mailto:support@gmail.com"
                    ><i class="icofont-support-faq mr-2"></i
                    >support@novena.com</a
                  >
                </li>
                <li class="list-inline-item">
                  <i class="icofont-location-pin mr-2"></i>Address Ta-134/A, New
                  York, USA
                </li>
              </ul>
            </div>
            <div class="col-lg-6">
              <div class="text-lg-right top-right-bar mt-2 mt-lg-0">
                <a href="tel:+23-345-67890">
                  <span>Call Now : </span>
                  <span class="h4">823-4565-13456</span>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <nav class="navbar navbar-expand-lg navigation" id="navbar">
        <div class="container">
          <a class="navbar-brand" href="index.html">
            <img
              src="{% static 'images/logo.png' %}"
              alt=""
              class="img-fluid"
            />
          </a>

          <button
            class="navbar-toggler collapsed"
            type="button"
            data-toggle="collapse"
            data-target="#navbarmain"
            aria-controls="navbarmain"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="icofont-navigation-menu"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarmain">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="index.html">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="about.html">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="service.html">Services</a>
              </li>

              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="department.html"
                  id="dropdown02"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                  >Department <i class="icofont-thin-down"></i
                ></a>
                <ul class="dropdown-menu" aria-labelledby="dropdown02">
                  <li>
                    <a class="dropdown-item" href="department.html"
                      >Departments</a
                    >
                  </li>
                  <li>
                    <a class="dropdown-item" href="department-single.html"
                      >Department Single</a
                    >
                  </li>
                </ul>
              </li>

              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="doctor.html"
                  id="dropdown03"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                  >Doctors <i class="icofont-thin-down"></i
                ></a>
                <ul class="dropdown-menu" aria-labelledby="dropdown03">
                  <li>
                    <a class="dropdown-item" href="doctor.html">Doctors</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="doctor-single.html"
                      >Doctor Single</a
                    >
                  </li>
                  <li>
                    <a class="dropdown-item" href="appoinment.html"
                      >Appoinment</a
                    >
                  </li>
                </ul>
              </li>

              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="{% url 'blog:post_list' %}"
                  id="dropdown05"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                  >Blog <i class="icofont-thin-down"></i
                ></a>
                <ul class="dropdown-menu" aria-labelledby="dropdown05">
                  
                  {% for categories_item in categories %}                   
                  <li>
                    <a class="dropdown-item" href="{{ categories_item.get_absolute_url }}">{{ categories_item.name }}</a>
                  </li>
                  {% endfor %}
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="contact.html">Contact</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>{% block content %} {% endblock content %}</main>

    <footer class="footer section gray-bg">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 mr-auto col-sm-6">
            <div class="widget mb-5 mb-lg-0">
              <div class="logo mb-4">
                <img
                  src="{% static 'images/logo.png' %}"
                  alt=""
                  class="img-fluid"
                />
              </div>
              <p>
                Tempora dolorem voluptatum nam vero assumenda voluptate, facilis
                ad eos obcaecati tenetur veritatis eveniet distinctio possimus.
              </p>

              <ul class="list-inline footer-socials mt-4">
                <li class="list-inline-item">
                  <a href="https://www.facebook.com/themefisher"
                    ><i class="icofont-facebook"></i
                  ></a>
                </li>
                <li class="list-inline-item">
                  <a href="https://twitter.com/themefisher"
                    ><i class="icofont-twitter"></i
                  ></a>
                </li>
                <li class="list-inline-item">
                  <a href="https://www.pinterest.com/themefisher/"
                    ><i class="icofont-linkedin"></i
                  ></a>
                </li>
              </ul>
            </div>
          </div>

          <div class="col-lg-2 col-md-6 col-sm-6">
            <div class="widget mb-5 mb-lg-0">
              <h4 class="text-capitalize mb-3">Department</h4>
              <div class="divider mb-4"></div>

              <ul class="list-unstyled footer-menu lh-35">
                <li><a href="#">Surgery </a></li>
                <li><a href="#">Wome's Health</a></li>
                <li><a href="#">Radiology</a></li>
                <li><a href="#">Cardioc</a></li>
                <li><a href="#">Medicine</a></li>
              </ul>
            </div>
          </div>

          <div class="col-lg-2 col-md-6 col-sm-6">
            <div class="widget mb-5 mb-lg-0">
              <h4 class="text-capitalize mb-3">Support</h4>
              <div class="divider mb-4"></div>

              <ul class="list-unstyled footer-menu lh-35">
                <li><a href="#">Terms & Conditions</a></li>
                <li><a href="#">Privacy Policy</a></li>
                <li><a href="#">Company Support </a></li>
                <li><a href="#">FAQuestions</a></li>
                <li><a href="#">Company Licence</a></li>
              </ul>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="widget widget-contact mb-5 mb-lg-0">
              <h4 class="text-capitalize mb-3">Get in Touch</h4>
              <div class="divider mb-4"></div>

              <div class="footer-contact-block mb-4">
                <div class="icon d-flex align-items-center">
                  <i class="icofont-email mr-3"></i>
                  <span class="h6 mb-0">Support Available for 24/7</span>
                </div>
                <h4 class="mt-2">
                  <a href="tel:+23-345-67890">Support@email.com</a>
                </h4>
              </div>

              <div class="footer-contact-block">
                <div class="icon d-flex align-items-center">
                  <i class="icofont-support mr-3"></i>
                  <span class="h6 mb-0">Mon to Fri : 08:30 - 18:00</span>
                </div>
                <h4 class="mt-2">
                  <a href="tel:+23-345-67890">+23-456-6588</a>
                </h4>
              </div>
            </div>
          </div>
        </div>

        <div class="footer-btm py-4 mt-5">
          <div class="row align-items-center justify-content-between">
            <div class="col-lg-6">
              <div class="copyright">
                &copy; Copyright Reserved to
                <span class="text-color">Novena</span> by
                <a href="https://themefisher.com/" target="_blank"
                  >Themefisher</a
                >
              </div>
            </div>
            <div class="col-lg-6">
              <div class="subscribe-form text-lg-right mt-5 mt-lg-0">
                <form action="#" class="subscribe">
                  <input
                    type="text"
                    class="form-control"
                    placeholder="Your Email address"
                  />
                  <a href="#" class="btn btn-main-2 btn-round-full"
                    >Subscribe</a
                  >
                </form>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-4">
              <a class="backtop js-scroll-trigger" href="#top">
                <i class="icofont-long-arrow-up"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </footer>

    <!-- Main jQuery -->
    <script src="{% static 'plugins/jquery/jquery.js' %}"></script>
    <!-- Bootstrap 4.3.2 -->
    <script src="{% static 'plugins/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/counterup/jquery.easing.js' %}"></script>
    <!-- Slick Slider -->
    <script src="{% static 'plugins/slick-carousel/slick/slick.min.js' %}"></script>
    <!-- Counterup -->
    <script src="{% static 'plugins/counterup/jquery.waypoints.min.js' %}"></script>

    <script src="{% static 'plugins/shuffle/shuffle.min.js' %}"></script>
    <script src="{% static 'plugins/counterup/jquery.counterup.min.js' %}"></script>
    <!-- Google Map -->
    <script src="{% static 'plugins/google-map/map.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAkeLMlsiwzp6b3Gnaxd86lvakimwGA6UA&callback=initMap"></script>

    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/contact.js' %}"></script>
  </body>
</html>